---
# tasks file for xentaurs-ansible-vpc
- name: Create new nat gateway and allocate new EIP.
  ec2_vpc_nat_gateway:
    state: present
    subnet_id: "{{ vpc_subnets.results[1].subnet.id }}"
    wait: yes
    if_exist_do_not_create: true
    region: "{{ aws_region }}"
  register: nat_gateway
