---
# tasks file for xentaurs-ansible-vpc
- name: Set up public subnet route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ aws_region }}"
    subnets:
      - "{{ vpc_subnets.results[0].subnet.id }}"
      - "{{ vpc_subnets.results[1].subnet.id }}"
      - "{{ vpc_subnets.results[2].subnet.id }}"
    routes:
      - dest:         "0.0.0.0/0"
        gateway_id:   "{{ igw.gateway_id }}"
    resource_tags: "{{ resource_tags }}"
