---
# tasks file for xentaurs-ansible-vpc
- name: Public Security Group
  ec2_group:
    description: Public SG
    name: public
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 1
        to_port: 65535
        cidr_ip: {{ aws_vpc_cidr_block }}
  register: pub_sg

  #- name: Debug vpc_subnets
  #debug: msg="{{ pub_sg }}"
